# Generated by Django 5.2.5 on 2025-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
