# Generated by Django 5.2.5 on 2025-09-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='authentication.department'),
        ),
    ]
