# Generated by Django 5.2.5 on 2025-09-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_city_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.country'),
        ),
    ]
